// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package line

import(
	"bytes"
	"context"
	"reflect"
	"database/sql/driver"
	"errors"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

type ErrorCode int64
const (
  ErrorCode_ILLEGAL_ARGUMENT ErrorCode = 0
  ErrorCode_AUTHENTICATION_FAILED ErrorCode = 1
  ErrorCode_DB_FAILED ErrorCode = 2
  ErrorCode_INVALID_STATE ErrorCode = 3
  ErrorCode_EXCESSIVE_ACCESS ErrorCode = 4
  ErrorCode_NOT_FOUND ErrorCode = 5
  ErrorCode_INVALID_LENGTH ErrorCode = 6
  ErrorCode_NOT_AVAILABLE_USER ErrorCode = 7
  ErrorCode_NOT_AUTHORIZED_DEVICE ErrorCode = 8
  ErrorCode_INVALID_MID ErrorCode = 9
  ErrorCode_NOT_A_MEMBER ErrorCode = 10
  ErrorCode_INCOMPATIBLE_APP_VERSION ErrorCode = 11
  ErrorCode_NOT_READY ErrorCode = 12
  ErrorCode_NOT_AVAILABLE_SESSION ErrorCode = 13
  ErrorCode_NOT_AUTHORIZED_SESSION ErrorCode = 14
  ErrorCode_SYSTEM_ERROR ErrorCode = 15
  ErrorCode_NO_AVAILABLE_VERIFICATION_METHOD ErrorCode = 16
  ErrorCode_NOT_AUTHENTICATED ErrorCode = 17
  ErrorCode_INVALID_IDENTITY_CREDENTIAL ErrorCode = 18
  ErrorCode_NOT_AVAILABLE_IDENTITY_IDENTIFIER ErrorCode = 19
  ErrorCode_INTERNAL_ERROR ErrorCode = 20
  ErrorCode_NO_SUCH_IDENTITY_IDENFIER ErrorCode = 21
  ErrorCode_DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY ErrorCode = 22
  ErrorCode_ILLEGAL_IDENTITY_CREDENTIAL ErrorCode = 23
  ErrorCode_UNKNOWN_CHANNEL ErrorCode = 24
  ErrorCode_NO_SUCH_MESSAGE_BOX ErrorCode = 25
  ErrorCode_NOT_AVAILABLE_MESSAGE_BOX ErrorCode = 26
  ErrorCode_CHANNEL_DOES_NOT_MATCH ErrorCode = 27
  ErrorCode_NOT_YOUR_MESSAGE ErrorCode = 28
  ErrorCode_MESSAGE_DEFINED_ERROR ErrorCode = 29
  ErrorCode_USER_CANNOT_ACCEPT_PRESENTS ErrorCode = 30
  ErrorCode_USER_NOT_STICKER_OWNER ErrorCode = 32
  ErrorCode_MAINTENANCE_ERROR ErrorCode = 33
  ErrorCode_ACCOUNT_NOT_MATCHED ErrorCode = 34
  ErrorCode_ABUSE_BLOCK ErrorCode = 35
  ErrorCode_NOT_FRIEND ErrorCode = 36
  ErrorCode_NOT_ALLOWED_CALL ErrorCode = 37
  ErrorCode_BLOCK_FRIEND ErrorCode = 38
  ErrorCode_INCOMPATIBLE_VOIP_VERSION ErrorCode = 39
  ErrorCode_INVALID_SNS_ACCESS_TOKEN ErrorCode = 40
  ErrorCode_EXTERNAL_SERVICE_NOT_AVAILABLE ErrorCode = 41
  ErrorCode_NOT_ALLOWED_ADD_CONTACT ErrorCode = 42
  ErrorCode_NOT_CERTIFICATED ErrorCode = 43
  ErrorCode_NOT_ALLOWED_SECONDARY_DEVICE ErrorCode = 44
  ErrorCode_INVALID_PIN_CODE ErrorCode = 45
  ErrorCode_NOT_FOUND_IDENTITY_CREDENTIAL ErrorCode = 46
  ErrorCode_EXCEED_FILE_MAX_SIZE ErrorCode = 47
  ErrorCode_EXCEED_DAILY_QUOTA ErrorCode = 48
  ErrorCode_NOT_SUPPORT_SEND_FILE ErrorCode = 49
  ErrorCode_MUST_UPGRADE ErrorCode = 50
  ErrorCode_NOT_AVAILABLE_PIN_CODE_SESSION ErrorCode = 51
  ErrorCode_EXPIRED_REVISION ErrorCode = 52
  ErrorCode_NOT_YET_PHONE_NUMBER ErrorCode = 54
  ErrorCode_BAD_CALL_NUMBER ErrorCode = 55
  ErrorCode_UNAVAILABLE_CALL_NUMBER ErrorCode = 56
  ErrorCode_NOT_SUPPORT_CALL_SERVICE ErrorCode = 57
  ErrorCode_CONGESTION_CONTROL ErrorCode = 58
  ErrorCode_NO_BALANCE ErrorCode = 59
  ErrorCode_NOT_PERMITTED_CALLER_ID ErrorCode = 60
  ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED ErrorCode = 61
  ErrorCode_CALLER_ID_VERIFICATION_REQUIRED ErrorCode = 62
  ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED ErrorCode = 63
  ErrorCode_MESSAGE_NOT_FOUND ErrorCode = 64
  ErrorCode_INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT ErrorCode = 65
  ErrorCode_ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED ErrorCode = 66
  ErrorCode_ACCOUNT_MIGRATION_PINCODE_BLOCKED ErrorCode = 67
  ErrorCode_INVALID_PASSWORD_FORMAT ErrorCode = 69
  ErrorCode_FEATURE_RESTRICTED ErrorCode = 70
  ErrorCode_MESSAGE_NOT_DESTRUCTIBLE ErrorCode = 71
  ErrorCode_PAID_CALL_REDEEM_FAILED ErrorCode = 72
  ErrorCode_PREVENTED_JOIN_BY_TICKET ErrorCode = 73
  ErrorCode_SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT ErrorCode = 75
  ErrorCode_SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY ErrorCode = 76
  ErrorCode_SECURITY_CENTER_NOT_VERIFIED ErrorCode = 77
  ErrorCode_SECURITY_CENTER_BLOCKED_BY_SETTING ErrorCode = 78
  ErrorCode_SECURITY_CENTER_BLOCKED ErrorCode = 79
  ErrorCode_TALK_PROXY_EXCEPTION ErrorCode = 80
  ErrorCode_E2EE_INVALID_PROTOCOL ErrorCode = 81
  ErrorCode_E2EE_RETRY_ENCRYPT ErrorCode = 82
  ErrorCode_E2EE_UPDATE_SENDER_KEY ErrorCode = 83
  ErrorCode_E2EE_UPDATE_RECEIVER_KEY ErrorCode = 84
  ErrorCode_E2EE_INVALID_ARGUMENT ErrorCode = 85
  ErrorCode_E2EE_INVALID_VERSION ErrorCode = 86
  ErrorCode_E2EE_SENDER_DISABLED ErrorCode = 87
  ErrorCode_E2EE_RECEIVER_DISABLED ErrorCode = 88
  ErrorCode_E2EE_SENDER_NOT_ALLOWED ErrorCode = 89
  ErrorCode_E2EE_RECEIVER_NOT_ALLOWED ErrorCode = 90
  ErrorCode_E2EE_RESEND_FAIL ErrorCode = 91
  ErrorCode_E2EE_RESEND_OK ErrorCode = 92
  ErrorCode_HITOKOTO_BACKUP_NO_AVAILABLE_DATA ErrorCode = 93
  ErrorCode_E2EE_UPDATE_PRIMARY_DEVICE ErrorCode = 94
  ErrorCode_SUCCESS ErrorCode = 95
  ErrorCode_CANCEL ErrorCode = 96
  ErrorCode_E2EE_PRIMARY_NOT_SUPPORT ErrorCode = 97
  ErrorCode_E2EE_RETRY_PLAIN ErrorCode = 98
  ErrorCode_E2EE_RECREATE_GROUP_KEY ErrorCode = 99
  ErrorCode_E2EE_GROUP_TOO_MANY_MEMBERS ErrorCode = 100
  ErrorCode_SERVER_BUSY ErrorCode = 101
  ErrorCode_NOT_ALLOWED_ADD_FOLLOW ErrorCode = 102
  ErrorCode_INCOMING_FRIEND_REQUEST_LIMIT ErrorCode = 103
  ErrorCode_OUTGOING_FRIEND_REQUEST_LIMIT ErrorCode = 104
  ErrorCode_OUTGOING_FRIEND_REQUEST_QUOTA ErrorCode = 105
  ErrorCode_DUPLICATED ErrorCode = 106
  ErrorCode_BANNED ErrorCode = 107
)

func (p ErrorCode) String() string {
  switch p {
  case ErrorCode_ILLEGAL_ARGUMENT: return "ILLEGAL_ARGUMENT"
  case ErrorCode_AUTHENTICATION_FAILED: return "AUTHENTICATION_FAILED"
  case ErrorCode_DB_FAILED: return "DB_FAILED"
  case ErrorCode_INVALID_STATE: return "INVALID_STATE"
  case ErrorCode_EXCESSIVE_ACCESS: return "EXCESSIVE_ACCESS"
  case ErrorCode_NOT_FOUND: return "NOT_FOUND"
  case ErrorCode_INVALID_LENGTH: return "INVALID_LENGTH"
  case ErrorCode_NOT_AVAILABLE_USER: return "NOT_AVAILABLE_USER"
  case ErrorCode_NOT_AUTHORIZED_DEVICE: return "NOT_AUTHORIZED_DEVICE"
  case ErrorCode_INVALID_MID: return "INVALID_MID"
  case ErrorCode_NOT_A_MEMBER: return "NOT_A_MEMBER"
  case ErrorCode_INCOMPATIBLE_APP_VERSION: return "INCOMPATIBLE_APP_VERSION"
  case ErrorCode_NOT_READY: return "NOT_READY"
  case ErrorCode_NOT_AVAILABLE_SESSION: return "NOT_AVAILABLE_SESSION"
  case ErrorCode_NOT_AUTHORIZED_SESSION: return "NOT_AUTHORIZED_SESSION"
  case ErrorCode_SYSTEM_ERROR: return "SYSTEM_ERROR"
  case ErrorCode_NO_AVAILABLE_VERIFICATION_METHOD: return "NO_AVAILABLE_VERIFICATION_METHOD"
  case ErrorCode_NOT_AUTHENTICATED: return "NOT_AUTHENTICATED"
  case ErrorCode_INVALID_IDENTITY_CREDENTIAL: return "INVALID_IDENTITY_CREDENTIAL"
  case ErrorCode_NOT_AVAILABLE_IDENTITY_IDENTIFIER: return "NOT_AVAILABLE_IDENTITY_IDENTIFIER"
  case ErrorCode_INTERNAL_ERROR: return "INTERNAL_ERROR"
  case ErrorCode_NO_SUCH_IDENTITY_IDENFIER: return "NO_SUCH_IDENTITY_IDENFIER"
  case ErrorCode_DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY: return "DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY"
  case ErrorCode_ILLEGAL_IDENTITY_CREDENTIAL: return "ILLEGAL_IDENTITY_CREDENTIAL"
  case ErrorCode_UNKNOWN_CHANNEL: return "UNKNOWN_CHANNEL"
  case ErrorCode_NO_SUCH_MESSAGE_BOX: return "NO_SUCH_MESSAGE_BOX"
  case ErrorCode_NOT_AVAILABLE_MESSAGE_BOX: return "NOT_AVAILABLE_MESSAGE_BOX"
  case ErrorCode_CHANNEL_DOES_NOT_MATCH: return "CHANNEL_DOES_NOT_MATCH"
  case ErrorCode_NOT_YOUR_MESSAGE: return "NOT_YOUR_MESSAGE"
  case ErrorCode_MESSAGE_DEFINED_ERROR: return "MESSAGE_DEFINED_ERROR"
  case ErrorCode_USER_CANNOT_ACCEPT_PRESENTS: return "USER_CANNOT_ACCEPT_PRESENTS"
  case ErrorCode_USER_NOT_STICKER_OWNER: return "USER_NOT_STICKER_OWNER"
  case ErrorCode_MAINTENANCE_ERROR: return "MAINTENANCE_ERROR"
  case ErrorCode_ACCOUNT_NOT_MATCHED: return "ACCOUNT_NOT_MATCHED"
  case ErrorCode_ABUSE_BLOCK: return "ABUSE_BLOCK"
  case ErrorCode_NOT_FRIEND: return "NOT_FRIEND"
  case ErrorCode_NOT_ALLOWED_CALL: return "NOT_ALLOWED_CALL"
  case ErrorCode_BLOCK_FRIEND: return "BLOCK_FRIEND"
  case ErrorCode_INCOMPATIBLE_VOIP_VERSION: return "INCOMPATIBLE_VOIP_VERSION"
  case ErrorCode_INVALID_SNS_ACCESS_TOKEN: return "INVALID_SNS_ACCESS_TOKEN"
  case ErrorCode_EXTERNAL_SERVICE_NOT_AVAILABLE: return "EXTERNAL_SERVICE_NOT_AVAILABLE"
  case ErrorCode_NOT_ALLOWED_ADD_CONTACT: return "NOT_ALLOWED_ADD_CONTACT"
  case ErrorCode_NOT_CERTIFICATED: return "NOT_CERTIFICATED"
  case ErrorCode_NOT_ALLOWED_SECONDARY_DEVICE: return "NOT_ALLOWED_SECONDARY_DEVICE"
  case ErrorCode_INVALID_PIN_CODE: return "INVALID_PIN_CODE"
  case ErrorCode_NOT_FOUND_IDENTITY_CREDENTIAL: return "NOT_FOUND_IDENTITY_CREDENTIAL"
  case ErrorCode_EXCEED_FILE_MAX_SIZE: return "EXCEED_FILE_MAX_SIZE"
  case ErrorCode_EXCEED_DAILY_QUOTA: return "EXCEED_DAILY_QUOTA"
  case ErrorCode_NOT_SUPPORT_SEND_FILE: return "NOT_SUPPORT_SEND_FILE"
  case ErrorCode_MUST_UPGRADE: return "MUST_UPGRADE"
  case ErrorCode_NOT_AVAILABLE_PIN_CODE_SESSION: return "NOT_AVAILABLE_PIN_CODE_SESSION"
  case ErrorCode_EXPIRED_REVISION: return "EXPIRED_REVISION"
  case ErrorCode_NOT_YET_PHONE_NUMBER: return "NOT_YET_PHONE_NUMBER"
  case ErrorCode_BAD_CALL_NUMBER: return "BAD_CALL_NUMBER"
  case ErrorCode_UNAVAILABLE_CALL_NUMBER: return "UNAVAILABLE_CALL_NUMBER"
  case ErrorCode_NOT_SUPPORT_CALL_SERVICE: return "NOT_SUPPORT_CALL_SERVICE"
  case ErrorCode_CONGESTION_CONTROL: return "CONGESTION_CONTROL"
  case ErrorCode_NO_BALANCE: return "NO_BALANCE"
  case ErrorCode_NOT_PERMITTED_CALLER_ID: return "NOT_PERMITTED_CALLER_ID"
  case ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED: return "NO_CALLER_ID_LIMIT_EXCEEDED"
  case ErrorCode_CALLER_ID_VERIFICATION_REQUIRED: return "CALLER_ID_VERIFICATION_REQUIRED"
  case ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED: return "NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED"
  case ErrorCode_MESSAGE_NOT_FOUND: return "MESSAGE_NOT_FOUND"
  case ErrorCode_INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT: return "INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT"
  case ErrorCode_ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED: return "ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED"
  case ErrorCode_ACCOUNT_MIGRATION_PINCODE_BLOCKED: return "ACCOUNT_MIGRATION_PINCODE_BLOCKED"
  case ErrorCode_INVALID_PASSWORD_FORMAT: return "INVALID_PASSWORD_FORMAT"
  case ErrorCode_FEATURE_RESTRICTED: return "FEATURE_RESTRICTED"
  case ErrorCode_MESSAGE_NOT_DESTRUCTIBLE: return "MESSAGE_NOT_DESTRUCTIBLE"
  case ErrorCode_PAID_CALL_REDEEM_FAILED: return "PAID_CALL_REDEEM_FAILED"
  case ErrorCode_PREVENTED_JOIN_BY_TICKET: return "PREVENTED_JOIN_BY_TICKET"
  case ErrorCode_SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT: return "SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT"
  case ErrorCode_SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY: return "SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY"
  case ErrorCode_SECURITY_CENTER_NOT_VERIFIED: return "SECURITY_CENTER_NOT_VERIFIED"
  case ErrorCode_SECURITY_CENTER_BLOCKED_BY_SETTING: return "SECURITY_CENTER_BLOCKED_BY_SETTING"
  case ErrorCode_SECURITY_CENTER_BLOCKED: return "SECURITY_CENTER_BLOCKED"
  case ErrorCode_TALK_PROXY_EXCEPTION: return "TALK_PROXY_EXCEPTION"
  case ErrorCode_E2EE_INVALID_PROTOCOL: return "E2EE_INVALID_PROTOCOL"
  case ErrorCode_E2EE_RETRY_ENCRYPT: return "E2EE_RETRY_ENCRYPT"
  case ErrorCode_E2EE_UPDATE_SENDER_KEY: return "E2EE_UPDATE_SENDER_KEY"
  case ErrorCode_E2EE_UPDATE_RECEIVER_KEY: return "E2EE_UPDATE_RECEIVER_KEY"
  case ErrorCode_E2EE_INVALID_ARGUMENT: return "E2EE_INVALID_ARGUMENT"
  case ErrorCode_E2EE_INVALID_VERSION: return "E2EE_INVALID_VERSION"
  case ErrorCode_E2EE_SENDER_DISABLED: return "E2EE_SENDER_DISABLED"
  case ErrorCode_E2EE_RECEIVER_DISABLED: return "E2EE_RECEIVER_DISABLED"
  case ErrorCode_E2EE_SENDER_NOT_ALLOWED: return "E2EE_SENDER_NOT_ALLOWED"
  case ErrorCode_E2EE_RECEIVER_NOT_ALLOWED: return "E2EE_RECEIVER_NOT_ALLOWED"
  case ErrorCode_E2EE_RESEND_FAIL: return "E2EE_RESEND_FAIL"
  case ErrorCode_E2EE_RESEND_OK: return "E2EE_RESEND_OK"
  case ErrorCode_HITOKOTO_BACKUP_NO_AVAILABLE_DATA: return "HITOKOTO_BACKUP_NO_AVAILABLE_DATA"
  case ErrorCode_E2EE_UPDATE_PRIMARY_DEVICE: return "E2EE_UPDATE_PRIMARY_DEVICE"
  case ErrorCode_SUCCESS: return "SUCCESS"
  case ErrorCode_CANCEL: return "CANCEL"
  case ErrorCode_E2EE_PRIMARY_NOT_SUPPORT: return "E2EE_PRIMARY_NOT_SUPPORT"
  case ErrorCode_E2EE_RETRY_PLAIN: return "E2EE_RETRY_PLAIN"
  case ErrorCode_E2EE_RECREATE_GROUP_KEY: return "E2EE_RECREATE_GROUP_KEY"
  case ErrorCode_E2EE_GROUP_TOO_MANY_MEMBERS: return "E2EE_GROUP_TOO_MANY_MEMBERS"
  case ErrorCode_SERVER_BUSY: return "SERVER_BUSY"
  case ErrorCode_NOT_ALLOWED_ADD_FOLLOW: return "NOT_ALLOWED_ADD_FOLLOW"
  case ErrorCode_INCOMING_FRIEND_REQUEST_LIMIT: return "INCOMING_FRIEND_REQUEST_LIMIT"
  case ErrorCode_OUTGOING_FRIEND_REQUEST_LIMIT: return "OUTGOING_FRIEND_REQUEST_LIMIT"
  case ErrorCode_OUTGOING_FRIEND_REQUEST_QUOTA: return "OUTGOING_FRIEND_REQUEST_QUOTA"
  case ErrorCode_DUPLICATED: return "DUPLICATED"
  case ErrorCode_BANNED: return "BANNED"
  }
  return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
  switch s {
  case "ILLEGAL_ARGUMENT": return ErrorCode_ILLEGAL_ARGUMENT, nil 
  case "AUTHENTICATION_FAILED": return ErrorCode_AUTHENTICATION_FAILED, nil 
  case "DB_FAILED": return ErrorCode_DB_FAILED, nil 
  case "INVALID_STATE": return ErrorCode_INVALID_STATE, nil 
  case "EXCESSIVE_ACCESS": return ErrorCode_EXCESSIVE_ACCESS, nil 
  case "NOT_FOUND": return ErrorCode_NOT_FOUND, nil 
  case "INVALID_LENGTH": return ErrorCode_INVALID_LENGTH, nil 
  case "NOT_AVAILABLE_USER": return ErrorCode_NOT_AVAILABLE_USER, nil 
  case "NOT_AUTHORIZED_DEVICE": return ErrorCode_NOT_AUTHORIZED_DEVICE, nil 
  case "INVALID_MID": return ErrorCode_INVALID_MID, nil 
  case "NOT_A_MEMBER": return ErrorCode_NOT_A_MEMBER, nil 
  case "INCOMPATIBLE_APP_VERSION": return ErrorCode_INCOMPATIBLE_APP_VERSION, nil 
  case "NOT_READY": return ErrorCode_NOT_READY, nil 
  case "NOT_AVAILABLE_SESSION": return ErrorCode_NOT_AVAILABLE_SESSION, nil 
  case "NOT_AUTHORIZED_SESSION": return ErrorCode_NOT_AUTHORIZED_SESSION, nil 
  case "SYSTEM_ERROR": return ErrorCode_SYSTEM_ERROR, nil 
  case "NO_AVAILABLE_VERIFICATION_METHOD": return ErrorCode_NO_AVAILABLE_VERIFICATION_METHOD, nil 
  case "NOT_AUTHENTICATED": return ErrorCode_NOT_AUTHENTICATED, nil 
  case "INVALID_IDENTITY_CREDENTIAL": return ErrorCode_INVALID_IDENTITY_CREDENTIAL, nil 
  case "NOT_AVAILABLE_IDENTITY_IDENTIFIER": return ErrorCode_NOT_AVAILABLE_IDENTITY_IDENTIFIER, nil 
  case "INTERNAL_ERROR": return ErrorCode_INTERNAL_ERROR, nil 
  case "NO_SUCH_IDENTITY_IDENFIER": return ErrorCode_NO_SUCH_IDENTITY_IDENFIER, nil 
  case "DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY": return ErrorCode_DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY, nil 
  case "ILLEGAL_IDENTITY_CREDENTIAL": return ErrorCode_ILLEGAL_IDENTITY_CREDENTIAL, nil 
  case "UNKNOWN_CHANNEL": return ErrorCode_UNKNOWN_CHANNEL, nil 
  case "NO_SUCH_MESSAGE_BOX": return ErrorCode_NO_SUCH_MESSAGE_BOX, nil 
  case "NOT_AVAILABLE_MESSAGE_BOX": return ErrorCode_NOT_AVAILABLE_MESSAGE_BOX, nil 
  case "CHANNEL_DOES_NOT_MATCH": return ErrorCode_CHANNEL_DOES_NOT_MATCH, nil 
  case "NOT_YOUR_MESSAGE": return ErrorCode_NOT_YOUR_MESSAGE, nil 
  case "MESSAGE_DEFINED_ERROR": return ErrorCode_MESSAGE_DEFINED_ERROR, nil 
  case "USER_CANNOT_ACCEPT_PRESENTS": return ErrorCode_USER_CANNOT_ACCEPT_PRESENTS, nil 
  case "USER_NOT_STICKER_OWNER": return ErrorCode_USER_NOT_STICKER_OWNER, nil 
  case "MAINTENANCE_ERROR": return ErrorCode_MAINTENANCE_ERROR, nil 
  case "ACCOUNT_NOT_MATCHED": return ErrorCode_ACCOUNT_NOT_MATCHED, nil 
  case "ABUSE_BLOCK": return ErrorCode_ABUSE_BLOCK, nil 
  case "NOT_FRIEND": return ErrorCode_NOT_FRIEND, nil 
  case "NOT_ALLOWED_CALL": return ErrorCode_NOT_ALLOWED_CALL, nil 
  case "BLOCK_FRIEND": return ErrorCode_BLOCK_FRIEND, nil 
  case "INCOMPATIBLE_VOIP_VERSION": return ErrorCode_INCOMPATIBLE_VOIP_VERSION, nil 
  case "INVALID_SNS_ACCESS_TOKEN": return ErrorCode_INVALID_SNS_ACCESS_TOKEN, nil 
  case "EXTERNAL_SERVICE_NOT_AVAILABLE": return ErrorCode_EXTERNAL_SERVICE_NOT_AVAILABLE, nil 
  case "NOT_ALLOWED_ADD_CONTACT": return ErrorCode_NOT_ALLOWED_ADD_CONTACT, nil 
  case "NOT_CERTIFICATED": return ErrorCode_NOT_CERTIFICATED, nil 
  case "NOT_ALLOWED_SECONDARY_DEVICE": return ErrorCode_NOT_ALLOWED_SECONDARY_DEVICE, nil 
  case "INVALID_PIN_CODE": return ErrorCode_INVALID_PIN_CODE, nil 
  case "NOT_FOUND_IDENTITY_CREDENTIAL": return ErrorCode_NOT_FOUND_IDENTITY_CREDENTIAL, nil 
  case "EXCEED_FILE_MAX_SIZE": return ErrorCode_EXCEED_FILE_MAX_SIZE, nil 
  case "EXCEED_DAILY_QUOTA": return ErrorCode_EXCEED_DAILY_QUOTA, nil 
  case "NOT_SUPPORT_SEND_FILE": return ErrorCode_NOT_SUPPORT_SEND_FILE, nil 
  case "MUST_UPGRADE": return ErrorCode_MUST_UPGRADE, nil 
  case "NOT_AVAILABLE_PIN_CODE_SESSION": return ErrorCode_NOT_AVAILABLE_PIN_CODE_SESSION, nil 
  case "EXPIRED_REVISION": return ErrorCode_EXPIRED_REVISION, nil 
  case "NOT_YET_PHONE_NUMBER": return ErrorCode_NOT_YET_PHONE_NUMBER, nil 
  case "BAD_CALL_NUMBER": return ErrorCode_BAD_CALL_NUMBER, nil 
  case "UNAVAILABLE_CALL_NUMBER": return ErrorCode_UNAVAILABLE_CALL_NUMBER, nil 
  case "NOT_SUPPORT_CALL_SERVICE": return ErrorCode_NOT_SUPPORT_CALL_SERVICE, nil 
  case "CONGESTION_CONTROL": return ErrorCode_CONGESTION_CONTROL, nil 
  case "NO_BALANCE": return ErrorCode_NO_BALANCE, nil 
  case "NOT_PERMITTED_CALLER_ID": return ErrorCode_NOT_PERMITTED_CALLER_ID, nil 
  case "NO_CALLER_ID_LIMIT_EXCEEDED": return ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED, nil 
  case "CALLER_ID_VERIFICATION_REQUIRED": return ErrorCode_CALLER_ID_VERIFICATION_REQUIRED, nil 
  case "NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED": return ErrorCode_NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED, nil 
  case "MESSAGE_NOT_FOUND": return ErrorCode_MESSAGE_NOT_FOUND, nil 
  case "INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT": return ErrorCode_INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT, nil 
  case "ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED": return ErrorCode_ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED, nil 
  case "ACCOUNT_MIGRATION_PINCODE_BLOCKED": return ErrorCode_ACCOUNT_MIGRATION_PINCODE_BLOCKED, nil 
  case "INVALID_PASSWORD_FORMAT": return ErrorCode_INVALID_PASSWORD_FORMAT, nil 
  case "FEATURE_RESTRICTED": return ErrorCode_FEATURE_RESTRICTED, nil 
  case "MESSAGE_NOT_DESTRUCTIBLE": return ErrorCode_MESSAGE_NOT_DESTRUCTIBLE, nil 
  case "PAID_CALL_REDEEM_FAILED": return ErrorCode_PAID_CALL_REDEEM_FAILED, nil 
  case "PREVENTED_JOIN_BY_TICKET": return ErrorCode_PREVENTED_JOIN_BY_TICKET, nil 
  case "SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT": return ErrorCode_SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT, nil 
  case "SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY": return ErrorCode_SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY, nil 
  case "SECURITY_CENTER_NOT_VERIFIED": return ErrorCode_SECURITY_CENTER_NOT_VERIFIED, nil 
  case "SECURITY_CENTER_BLOCKED_BY_SETTING": return ErrorCode_SECURITY_CENTER_BLOCKED_BY_SETTING, nil 
  case "SECURITY_CENTER_BLOCKED": return ErrorCode_SECURITY_CENTER_BLOCKED, nil 
  case "TALK_PROXY_EXCEPTION": return ErrorCode_TALK_PROXY_EXCEPTION, nil 
  case "E2EE_INVALID_PROTOCOL": return ErrorCode_E2EE_INVALID_PROTOCOL, nil 
  case "E2EE_RETRY_ENCRYPT": return ErrorCode_E2EE_RETRY_ENCRYPT, nil 
  case "E2EE_UPDATE_SENDER_KEY": return ErrorCode_E2EE_UPDATE_SENDER_KEY, nil 
  case "E2EE_UPDATE_RECEIVER_KEY": return ErrorCode_E2EE_UPDATE_RECEIVER_KEY, nil 
  case "E2EE_INVALID_ARGUMENT": return ErrorCode_E2EE_INVALID_ARGUMENT, nil 
  case "E2EE_INVALID_VERSION": return ErrorCode_E2EE_INVALID_VERSION, nil 
  case "E2EE_SENDER_DISABLED": return ErrorCode_E2EE_SENDER_DISABLED, nil 
  case "E2EE_RECEIVER_DISABLED": return ErrorCode_E2EE_RECEIVER_DISABLED, nil 
  case "E2EE_SENDER_NOT_ALLOWED": return ErrorCode_E2EE_SENDER_NOT_ALLOWED, nil 
  case "E2EE_RECEIVER_NOT_ALLOWED": return ErrorCode_E2EE_RECEIVER_NOT_ALLOWED, nil 
  case "E2EE_RESEND_FAIL": return ErrorCode_E2EE_RESEND_FAIL, nil 
  case "E2EE_RESEND_OK": return ErrorCode_E2EE_RESEND_OK, nil 
  case "HITOKOTO_BACKUP_NO_AVAILABLE_DATA": return ErrorCode_HITOKOTO_BACKUP_NO_AVAILABLE_DATA, nil 
  case "E2EE_UPDATE_PRIMARY_DEVICE": return ErrorCode_E2EE_UPDATE_PRIMARY_DEVICE, nil 
  case "SUCCESS": return ErrorCode_SUCCESS, nil 
  case "CANCEL": return ErrorCode_CANCEL, nil 
  case "E2EE_PRIMARY_NOT_SUPPORT": return ErrorCode_E2EE_PRIMARY_NOT_SUPPORT, nil 
  case "E2EE_RETRY_PLAIN": return ErrorCode_E2EE_RETRY_PLAIN, nil 
  case "E2EE_RECREATE_GROUP_KEY": return ErrorCode_E2EE_RECREATE_GROUP_KEY, nil 
  case "E2EE_GROUP_TOO_MANY_MEMBERS": return ErrorCode_E2EE_GROUP_TOO_MANY_MEMBERS, nil 
  case "SERVER_BUSY": return ErrorCode_SERVER_BUSY, nil 
  case "NOT_ALLOWED_ADD_FOLLOW": return ErrorCode_NOT_ALLOWED_ADD_FOLLOW, nil 
  case "INCOMING_FRIEND_REQUEST_LIMIT": return ErrorCode_INCOMING_FRIEND_REQUEST_LIMIT, nil 
  case "OUTGOING_FRIEND_REQUEST_LIMIT": return ErrorCode_OUTGOING_FRIEND_REQUEST_LIMIT, nil 
  case "OUTGOING_FRIEND_REQUEST_QUOTA": return ErrorCode_OUTGOING_FRIEND_REQUEST_QUOTA, nil 
  case "DUPLICATED": return ErrorCode_DUPLICATED, nil 
  case "BANNED": return ErrorCode_BANNED, nil 
  }
  return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}


func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }

func (p ErrorCode) MarshalText() ([]byte, error) {
return []byte(p.String()), nil
}

func (p *ErrorCode) UnmarshalText(text []byte) error {
q, err := ErrorCodeFromString(string(text))
if (err != nil) {
return err
}
*p = q
return nil
}

func (p *ErrorCode) Scan(value interface{}) error {
v, ok := value.(int64)
if !ok {
return errors.New("Scan value is not int64")
}
*p = ErrorCode(v)
return nil
}

func (p * ErrorCode) Value() (driver.Value, error) {
  if p == nil {
    return nil, nil
  }
return int64(*p), nil
}
// Attributes:
//  - CreatorMid
//  - CreatedTime
//  - ChatRoomBGMInfo
type ChatRoomBGM struct {
  CreatorMid string `thrift:"creatorMid,1" db:"creatorMid" json:"creatorMid"`
  CreatedTime int64 `thrift:"createdTime,2" db:"createdTime" json:"createdTime"`
  ChatRoomBGMInfo string `thrift:"chatRoomBGMInfo,3" db:"chatRoomBGMInfo" json:"chatRoomBGMInfo"`
}

func NewChatRoomBGM() *ChatRoomBGM {
  return &ChatRoomBGM{}
}


func (p *ChatRoomBGM) GetCreatorMid() string {
  return p.CreatorMid
}

func (p *ChatRoomBGM) GetCreatedTime() int64 {
  return p.CreatedTime
}

func (p *ChatRoomBGM) GetChatRoomBGMInfo() string {
  return p.ChatRoomBGMInfo
}
func (p *ChatRoomBGM) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField3(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ChatRoomBGM)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.CreatorMid = v
}
  return nil
}

func (p *ChatRoomBGM)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.CreatedTime = v
}
  return nil
}

func (p *ChatRoomBGM)  ReadField3(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.ChatRoomBGMInfo = v
}
  return nil
}

func (p *ChatRoomBGM) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("ChatRoomBGM"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ChatRoomBGM) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("creatorMid", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:creatorMid: ", p), err) }
  if err := oprot.WriteString(string(p.CreatorMid)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.creatorMid (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:creatorMid: ", p), err) }
  return err
}

func (p *ChatRoomBGM) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("createdTime", thrift.I64, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:createdTime: ", p), err) }
  if err := oprot.WriteI64(int64(p.CreatedTime)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.createdTime (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:createdTime: ", p), err) }
  return err
}

func (p *ChatRoomBGM) writeField3(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("chatRoomBGMInfo", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:chatRoomBGMInfo: ", p), err) }
  if err := oprot.WriteString(string(p.ChatRoomBGMInfo)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.chatRoomBGMInfo (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:chatRoomBGMInfo: ", p), err) }
  return err
}

func (p *ChatRoomBGM) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ChatRoomBGM(%+v)", *p)
}

// Attributes:
//  - Code
//  - Reason
//  - ParameterMap
type TalkException struct {
  Code ErrorCode `thrift:"code,1" db:"code" json:"code"`
  Reason string `thrift:"reason,2" db:"reason" json:"reason"`
  ParameterMap map[string]string `thrift:"parameterMap,3" db:"parameterMap" json:"parameterMap"`
}

func NewTalkException() *TalkException {
  return &TalkException{}
}


func (p *TalkException) GetCode() ErrorCode {
  return p.Code
}

func (p *TalkException) GetReason() string {
  return p.Reason
}

func (p *TalkException) GetParameterMap() map[string]string {
  return p.ParameterMap
}
func (p *TalkException) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.MAP {
        if err := p.ReadField3(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TalkException)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := ErrorCode(v)
  p.Code = temp
}
  return nil
}

func (p *TalkException)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Reason = v
}
  return nil
}

func (p *TalkException)  ReadField3(iprot thrift.TProtocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string]string, size)
  p.ParameterMap =  tMap
  for i := 0; i < size; i ++ {
var _key0 string
    if v, err := iprot.ReadString(); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _key0 = v
}
var _val1 string
    if v, err := iprot.ReadString(); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _val1 = v
}
    p.ParameterMap[_key0] = _val1
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *TalkException) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("TalkException"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TalkException) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("code", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:code: ", p), err) }
  if err := oprot.WriteI32(int32(p.Code)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.code (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:code: ", p), err) }
  return err
}

func (p *TalkException) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("reason", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:reason: ", p), err) }
  if err := oprot.WriteString(string(p.Reason)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.reason (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:reason: ", p), err) }
  return err
}

func (p *TalkException) writeField3(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("parameterMap", thrift.MAP, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:parameterMap: ", p), err) }
  if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.ParameterMap)); err != nil {
    return thrift.PrependError("error writing map begin: ", err)
  }
  for k, v := range p.ParameterMap {
    if err := oprot.WriteString(string(k)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
    if err := oprot.WriteString(string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteMapEnd(); err != nil {
    return thrift.PrependError("error writing map end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:parameterMap: ", p), err) }
  return err
}

func (p *TalkException) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TalkException(%+v)", *p)
}

func (p *TalkException) Error() string {
  return p.String()
}

type TalkService interface {
  // Parameters:
  //  - ChatRoomMids
  GetChatRoomBGMs(ctx context.Context, chatRoomMids []string) (r map[string]*ChatRoomBGM, err error)
  // Parameters:
  //  - ReqSeq
  //  - ChatRoomMid
  //  - ChatRoomBGMInfo
  UpdateChatRoomBGM(ctx context.Context, reqSeq int32, chatRoomMid string, chatRoomBGMInfo string) (r *ChatRoomBGM, err error)
}

type TalkServiceClient struct {
  c thrift.TClient
}

func NewTalkServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TalkServiceClient {
  return &TalkServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewTalkServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TalkServiceClient {
  return &TalkServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewTalkServiceClient(c thrift.TClient) *TalkServiceClient {
  return &TalkServiceClient{
    c: c,
  }
}

func (p *TalkServiceClient) Client_() thrift.TClient {
  return p.c
}
// Parameters:
//  - ChatRoomMids
func (p *TalkServiceClient) GetChatRoomBGMs(ctx context.Context, chatRoomMids []string) (r map[string]*ChatRoomBGM, err error) {
  var _args2 TalkServiceGetChatRoomBGMsArgs
  _args2.ChatRoomMids = chatRoomMids
  var _result3 TalkServiceGetChatRoomBGMsResult
  if err = p.Client_().Call(ctx, "getChatRoomBGMs", &_args2, &_result3); err != nil {
    return
  }
  switch {
  case _result3.E!= nil:
    return r, _result3.E
  }

  return _result3.GetSuccess(), nil
}

// Parameters:
//  - ReqSeq
//  - ChatRoomMid
//  - ChatRoomBGMInfo
func (p *TalkServiceClient) UpdateChatRoomBGM(ctx context.Context, reqSeq int32, chatRoomMid string, chatRoomBGMInfo string) (r *ChatRoomBGM, err error) {
  var _args4 TalkServiceUpdateChatRoomBGMArgs
  _args4.ReqSeq = reqSeq
  _args4.ChatRoomMid = chatRoomMid
  _args4.ChatRoomBGMInfo = chatRoomBGMInfo
  var _result5 TalkServiceUpdateChatRoomBGMResult
  if err = p.Client_().Call(ctx, "updateChatRoomBGM", &_args4, &_result5); err != nil {
    return
  }
  switch {
  case _result5.E!= nil:
    return r, _result5.E
  }

  return _result5.GetSuccess(), nil
}

type TalkServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler TalkService
}

func (p *TalkServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *TalkServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *TalkServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewTalkServiceProcessor(handler TalkService) *TalkServiceProcessor {

  self6 := &TalkServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self6.processorMap["getChatRoomBGMs"] = &talkServiceProcessorGetChatRoomBGMs{handler:handler}
  self6.processorMap["updateChatRoomBGM"] = &talkServiceProcessorUpdateChatRoomBGM{handler:handler}
return self6
}

func (p *TalkServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x7 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x7.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush(ctx)
  return false, x7

}

type talkServiceProcessorGetChatRoomBGMs struct {
  handler TalkService
}

func (p *talkServiceProcessorGetChatRoomBGMs) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := TalkServiceGetChatRoomBGMsArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("getChatRoomBGMs", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := TalkServiceGetChatRoomBGMsResult{}
var retval map[string]*ChatRoomBGM
  var err2 error
  if retval, err2 = p.handler.GetChatRoomBGMs(ctx, args.ChatRoomMids); err2 != nil {
  switch v := err2.(type) {
    case *TalkException:
  result.E = v
    default:
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getChatRoomBGMs: " + err2.Error())
    oprot.WriteMessageBegin("getChatRoomBGMs", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  }
  } else {
    result.Success = retval
}
  if err2 = oprot.WriteMessageBegin("getChatRoomBGMs", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}

type talkServiceProcessorUpdateChatRoomBGM struct {
  handler TalkService
}

func (p *talkServiceProcessorUpdateChatRoomBGM) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := TalkServiceUpdateChatRoomBGMArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("updateChatRoomBGM", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return false, err
  }

  iprot.ReadMessageEnd()
  result := TalkServiceUpdateChatRoomBGMResult{}
var retval *ChatRoomBGM
  var err2 error
  if retval, err2 = p.handler.UpdateChatRoomBGM(ctx, args.ReqSeq, args.ChatRoomMid, args.ChatRoomBGMInfo); err2 != nil {
  switch v := err2.(type) {
    case *TalkException:
  result.E = v
    default:
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing updateChatRoomBGM: " + err2.Error())
    oprot.WriteMessageBegin("updateChatRoomBGM", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush(ctx)
    return true, err2
  }
  } else {
    result.Success = retval
}
  if err2 = oprot.WriteMessageBegin("updateChatRoomBGM", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - ChatRoomMids
type TalkServiceGetChatRoomBGMsArgs struct {
  // unused field # 1
  ChatRoomMids []string `thrift:"chatRoomMids,2" db:"chatRoomMids" json:"chatRoomMids"`
}

func NewTalkServiceGetChatRoomBGMsArgs() *TalkServiceGetChatRoomBGMsArgs {
  return &TalkServiceGetChatRoomBGMsArgs{}
}


func (p *TalkServiceGetChatRoomBGMsArgs) GetChatRoomMids() []string {
  return p.ChatRoomMids
}
func (p *TalkServiceGetChatRoomBGMsArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 2:
      if fieldTypeId == thrift.SET {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsArgs)  ReadField2(iprot thrift.TProtocol) error {
  _, size, err := iprot.ReadSetBegin()
  if err != nil {
    return thrift.PrependError("error reading set begin: ", err)
  }
  tSet := make([]string, 0, size)
  p.ChatRoomMids =  tSet
  for i := 0; i < size; i ++ {
var _elem8 string
    if v, err := iprot.ReadString(); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _elem8 = v
}
    p.ChatRoomMids = append(p.ChatRoomMids, _elem8)
  }
  if err := iprot.ReadSetEnd(); err != nil {
    return thrift.PrependError("error reading set end: ", err)
  }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("getChatRoomBGMs_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsArgs) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("chatRoomMids", thrift.SET, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:chatRoomMids: ", p), err) }
  if err := oprot.WriteSetBegin(thrift.STRING, len(p.ChatRoomMids)); err != nil {
    return thrift.PrependError("error writing set begin: ", err)
  }
  for i := 0; i<len(p.ChatRoomMids); i++ {
    for j := i+1; j<len(p.ChatRoomMids); j++ {
      if reflect.DeepEqual(p.ChatRoomMids[i],p.ChatRoomMids[j]) { 
        return thrift.PrependError("", fmt.Errorf("%T error writing set field: slice is not unique", p.ChatRoomMids[i]))
      }
    }
  }
  for _, v := range p.ChatRoomMids {
    if err := oprot.WriteString(string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteSetEnd(); err != nil {
    return thrift.PrependError("error writing set end: ", err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:chatRoomMids: ", p), err) }
  return err
}

func (p *TalkServiceGetChatRoomBGMsArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TalkServiceGetChatRoomBGMsArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - E
type TalkServiceGetChatRoomBGMsResult struct {
  Success map[string]*ChatRoomBGM `thrift:"success,0" db:"success" json:"success,omitempty"`
  E *TalkException `thrift:"e,1" db:"e" json:"e,omitempty"`
}

func NewTalkServiceGetChatRoomBGMsResult() *TalkServiceGetChatRoomBGMsResult {
  return &TalkServiceGetChatRoomBGMsResult{}
}

var TalkServiceGetChatRoomBGMsResult_Success_DEFAULT map[string]*ChatRoomBGM

func (p *TalkServiceGetChatRoomBGMsResult) GetSuccess() map[string]*ChatRoomBGM {
  return p.Success
}
var TalkServiceGetChatRoomBGMsResult_E_DEFAULT *TalkException
func (p *TalkServiceGetChatRoomBGMsResult) GetE() *TalkException {
  if !p.IsSetE() {
    return TalkServiceGetChatRoomBGMsResult_E_DEFAULT
  }
return p.E
}
func (p *TalkServiceGetChatRoomBGMsResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *TalkServiceGetChatRoomBGMsResult) IsSetE() bool {
  return p.E != nil
}

func (p *TalkServiceGetChatRoomBGMsResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.MAP {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsResult)  ReadField0(iprot thrift.TProtocol) error {
  _, _, size, err := iprot.ReadMapBegin()
  if err != nil {
    return thrift.PrependError("error reading map begin: ", err)
  }
  tMap := make(map[string]*ChatRoomBGM, size)
  p.Success =  tMap
  for i := 0; i < size; i ++ {
var _key9 string
    if v, err := iprot.ReadString(); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _key9 = v
}
    _val10 := &ChatRoomBGM{}
    if err := _val10.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val10), err)
    }
    p.Success[_key9] = _val10
  }
  if err := iprot.ReadMapEnd(); err != nil {
    return thrift.PrependError("error reading map end: ", err)
  }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsResult)  ReadField1(iprot thrift.TProtocol) error {
  p.E = &TalkException{}
  if err := p.E.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.E), err)
  }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("getChatRoomBGMs_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
    if err := p.writeField1(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TalkServiceGetChatRoomBGMsResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.MAP, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Success)); err != nil {
      return thrift.PrependError("error writing map begin: ", err)
    }
    for k, v := range p.Success {
      if err := oprot.WriteString(string(k)); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteMapEnd(); err != nil {
      return thrift.PrependError("error writing map end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *TalkServiceGetChatRoomBGMsResult) writeField1(oprot thrift.TProtocol) (err error) {
  if p.IsSetE() {
    if err := oprot.WriteFieldBegin("e", thrift.STRUCT, 1); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err) }
    if err := p.E.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.E), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err) }
  }
  return err
}

func (p *TalkServiceGetChatRoomBGMsResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TalkServiceGetChatRoomBGMsResult(%+v)", *p)
}

// Attributes:
//  - ReqSeq
//  - ChatRoomMid
//  - ChatRoomBGMInfo
type TalkServiceUpdateChatRoomBGMArgs struct {
  ReqSeq int32 `thrift:"reqSeq,1" db:"reqSeq" json:"reqSeq"`
  ChatRoomMid string `thrift:"chatRoomMid,2" db:"chatRoomMid" json:"chatRoomMid"`
  ChatRoomBGMInfo string `thrift:"chatRoomBGMInfo,3" db:"chatRoomBGMInfo" json:"chatRoomBGMInfo"`
}

func NewTalkServiceUpdateChatRoomBGMArgs() *TalkServiceUpdateChatRoomBGMArgs {
  return &TalkServiceUpdateChatRoomBGMArgs{}
}


func (p *TalkServiceUpdateChatRoomBGMArgs) GetReqSeq() int32 {
  return p.ReqSeq
}

func (p *TalkServiceUpdateChatRoomBGMArgs) GetChatRoomMid() string {
  return p.ChatRoomMid
}

func (p *TalkServiceUpdateChatRoomBGMArgs) GetChatRoomBGMInfo() string {
  return p.ChatRoomBGMInfo
}
func (p *TalkServiceUpdateChatRoomBGMArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField3(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMArgs)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ReqSeq = v
}
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMArgs)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.ChatRoomMid = v
}
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMArgs)  ReadField3(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.ChatRoomBGMInfo = v
}
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("updateChatRoomBGM_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("reqSeq", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:reqSeq: ", p), err) }
  if err := oprot.WriteI32(int32(p.ReqSeq)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.reqSeq (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:reqSeq: ", p), err) }
  return err
}

func (p *TalkServiceUpdateChatRoomBGMArgs) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("chatRoomMid", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:chatRoomMid: ", p), err) }
  if err := oprot.WriteString(string(p.ChatRoomMid)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.chatRoomMid (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:chatRoomMid: ", p), err) }
  return err
}

func (p *TalkServiceUpdateChatRoomBGMArgs) writeField3(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("chatRoomBGMInfo", thrift.STRING, 3); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:chatRoomBGMInfo: ", p), err) }
  if err := oprot.WriteString(string(p.ChatRoomBGMInfo)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.chatRoomBGMInfo (3) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 3:chatRoomBGMInfo: ", p), err) }
  return err
}

func (p *TalkServiceUpdateChatRoomBGMArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TalkServiceUpdateChatRoomBGMArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - E
type TalkServiceUpdateChatRoomBGMResult struct {
  Success *ChatRoomBGM `thrift:"success,0" db:"success" json:"success,omitempty"`
  E *TalkException `thrift:"e,1" db:"e" json:"e,omitempty"`
}

func NewTalkServiceUpdateChatRoomBGMResult() *TalkServiceUpdateChatRoomBGMResult {
  return &TalkServiceUpdateChatRoomBGMResult{}
}

var TalkServiceUpdateChatRoomBGMResult_Success_DEFAULT *ChatRoomBGM
func (p *TalkServiceUpdateChatRoomBGMResult) GetSuccess() *ChatRoomBGM {
  if !p.IsSetSuccess() {
    return TalkServiceUpdateChatRoomBGMResult_Success_DEFAULT
  }
return p.Success
}
var TalkServiceUpdateChatRoomBGMResult_E_DEFAULT *TalkException
func (p *TalkServiceUpdateChatRoomBGMResult) GetE() *TalkException {
  if !p.IsSetE() {
    return TalkServiceUpdateChatRoomBGMResult_E_DEFAULT
  }
return p.E
}
func (p *TalkServiceUpdateChatRoomBGMResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *TalkServiceUpdateChatRoomBGMResult) IsSetE() bool {
  return p.E != nil
}

func (p *TalkServiceUpdateChatRoomBGMResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMResult)  ReadField0(iprot thrift.TProtocol) error {
  p.Success = &ChatRoomBGM{}
  if err := p.Success.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMResult)  ReadField1(iprot thrift.TProtocol) error {
  p.E = &TalkException{}
  if err := p.E.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.E), err)
  }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("updateChatRoomBGM_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
    if err := p.writeField1(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TalkServiceUpdateChatRoomBGMResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *TalkServiceUpdateChatRoomBGMResult) writeField1(oprot thrift.TProtocol) (err error) {
  if p.IsSetE() {
    if err := oprot.WriteFieldBegin("e", thrift.STRUCT, 1); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:e: ", p), err) }
    if err := p.E.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.E), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 1:e: ", p), err) }
  }
  return err
}

func (p *TalkServiceUpdateChatRoomBGMResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TalkServiceUpdateChatRoomBGMResult(%+v)", *p)
}


